# Generated by Django 5.0.2 on 2024-02-18 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('school', models.CharField(max_length=3000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('cert_url', models.URLField(blank=True)),
                ('starte_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_enrolled', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='infoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('infoImage', models.ImageField(null=True, upload_to='')),
                ('role', models.CharField(max_length=500)),
                ('heroImage', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
