# Generated by Django 5.0.2 on 2024-02-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='starte_date',
            new_name='started_date',
        ),
    ]
