# Generated by Django 5.0.2 on 2024-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_starte_date_education_started_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('country', models.TextField()),
                ('member_image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('role', models.CharField(choices=[('vocals', 'Vocals'), ('guitars', 'Guitars'), ('bass', 'Bass'), ('keyboards', 'Keyboards'), ('tin whistle', 'Tin Whistle'), ('lyre', 'Lyre'), ('mix', 'Mix'), ('master', 'Master')], default='vocals', max_length=12)),
                ('equipament', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='infoPage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
