# Generated by Django 5.0.2 on 2024-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_delete_education_delete_infopage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
