# Generated by Django 5.0.2 on 2024-02-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('emblem', models.ImageField(null=True, upload_to='')),
                ('label', models.CharField(max_length=1000)),
                ('management', models.CharField(max_length=2000)),
                ('press_request', models.CharField(max_length=2000)),
                ('booking', models.CharField(max_length=2000)),
            ],
        ),
    ]
