# Generated by Django 5.0.2 on 2024-02-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='booking',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='label',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='management',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='press_request',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
