# Generated by Django 5.0.2 on 2024-02-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_about_booking_alter_about_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='booking_email',
            field=models.EmailField(default='elenionofficial@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='about',
            name='label_email',
            field=models.EmailField(default='kublaikapsalis@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='about',
            name='management_email',
            field=models.EmailField(default='elenionofficial@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='about',
            name='press_email',
            field=models.EmailField(default='elenionofficial@gmail.com', max_length=254),
        ),
    ]
