# Generated by Django 5.0.2 on 2024-02-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_booking_email_about_label_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='booking_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='about',
            name='label_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='about',
            name='management_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='about',
            name='press_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
