# Generated by Django 5.0.2 on 2024-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_new_testimonial_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='original_post',
            field=models.URLField(blank=True, null=True),
        ),
    ]
