# Generated by Django 5.0.2 on 2024-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_new_original_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
        migrations.AddField(
            model_name='new',
            name='first_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='second_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
