# Generated by Django 5.0.2 on 2024-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_new_description_new_first_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='original_released_date',
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
