# Generated by Django 5.0.2 on 2024-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_new_original_released_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='original_released_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
