# Generated by Django 5.0.2 on 2024-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_new_original_released_date_alter_new_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='testimonial',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='testimonial_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='testimonial_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
