# Generated by Django 5.0.2 on 2024-03-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_about_testimonial_about_testimonial_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.ManyToManyField(blank=True, related_name='musics', to='core.music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.album'),
        ),
    ]
