# Generated by Django 5.0.2 on 2024-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('grey', 'Grey')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, choices=[('in stock', 'In Stock'), ('sold out', 'Sold Out')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_format',
            field=models.CharField(blank=True, choices=[('lp', 'LP'), ('vinyl', 'Vinyl'), ('poster', 'Poster')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('xx-small', 'XXS'), ('x-small', 'XS'), ('small', 'S'), ('medium', 'M'), ('large', 'L'), ('x-large', 'XL'), ('xx-large', 'XXL')], max_length=10, null=True),
        ),
    ]
